package cn.chinapost.jdpt.pda.pickup.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.com.fyl.learn.mysendmsgapp.localdata.TTempPlateContent;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TTEMP_PLATE_CONTENT".
*/
public class TTempPlateContentDao extends AbstractDao<TTempPlateContent, Void> {

    public static final String TABLENAME = "TTEMP_PLATE_CONTENT";

    /**
     * Properties of entity TTempPlateContent.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Content = new Property(0, String.class, "content", false, "CONTENT");
    }


    public TTempPlateContentDao(DaoConfig config) {
        super(config);
    }
    
    public TTempPlateContentDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TTEMP_PLATE_CONTENT\" (" + //
                "\"CONTENT\" TEXT);"); // 0: content
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TTEMP_PLATE_CONTENT\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TTempPlateContent entity) {
        stmt.clearBindings();
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(1, content);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TTempPlateContent entity) {
        stmt.clearBindings();
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(1, content);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public TTempPlateContent readEntity(Cursor cursor, int offset) {
        TTempPlateContent entity = new TTempPlateContent( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // content
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TTempPlateContent entity, int offset) {
        entity.setContent(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(TTempPlateContent entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(TTempPlateContent entity) {
        return null;
    }

    @Override
    public boolean hasKey(TTempPlateContent entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
