package cn.chinapost.jdpt.pda.pickup.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.com.fyl.learn.mysendmsgapp.localdata.TTemplate;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TTEMPLATE".
*/
public class TTemplateDao extends AbstractDao<TTemplate, Void> {

    public static final String TABLENAME = "TTEMPLATE";

    /**
     * Properties of entity TTemplate.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Time = new Property(0, String.class, "time", false, "TIME");
    }


    public TTemplateDao(DaoConfig config) {
        super(config);
    }
    
    public TTemplateDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TTEMPLATE\" (" + //
                "\"TIME\" TEXT);"); // 0: time
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TTEMPLATE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TTemplate entity) {
        stmt.clearBindings();
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(1, time);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TTemplate entity) {
        stmt.clearBindings();
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(1, time);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public TTemplate readEntity(Cursor cursor, int offset) {
        TTemplate entity = new TTemplate( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0) // time
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TTemplate entity, int offset) {
        entity.setTime(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(TTemplate entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(TTemplate entity) {
        return null;
    }

    @Override
    public boolean hasKey(TTemplate entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
